from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "Content"
OUTPUT_PATH = ROOT / "Source" / "Assets.cs"

SECTIONS = (
    ("Maps", CONTENT_DIR / "Levels", {".tmx"}),
    ("Sprites", CONTENT_DIR / "Sprites", {".png", ".jpg", ".jpeg"}),
    ("Sfx", CONTENT_DIR / "Sfx", {".wav"}),
    ("Music", CONTENT_DIR / "Music", {".ogg"}),
)


def to_pascal_token(token: str) -> str:
    if token.isdigit():
        return token

    return token[:1].upper() + token[1:]


def constant_name(stem: str) -> str:
    tokens = [to_pascal_token(token) for token in re.split(r"[^A-Za-z0-9]+", stem) if token]
    if not tokens:
        return "_"

    if (
        len(tokens) > 2
        and tokens[0].lower() == "world"
        and all(token.isdigit() for token in tokens[1:])
    ):
        name = f"{tokens[0]}{tokens[1]}_{'_'.join(tokens[2:])}"
    else:
        name = "".join(tokens)

    if not (name[0].isalpha() or name[0] == "_"):
        name = f"_{name}"

    return name


def content_path(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def iter_assets(folder: Path, extensions: set[str]) -> list[Path]:
    if not folder.exists():
        return []

    return sorted(
        path
        for path in folder.iterdir()
        if path.is_file() and path.suffix.lower() in extensions
    )


def generate() -> str:
    lines: list[str] = [
        "namespace SuperMario",
        "{",
        "    /// <summary>",
        "    /// class that contains the names of all runtime content files",
        "    /// </summary>",
        "    /// <remarks>",
        "    /// Auto-generated by Tools/generate_assets.py. Re-run after adding,",
        "    /// removing, or renaming files under Content.",
        "    /// </remarks>",
        "    class Assets",
        "    {",
    ]

    for section_name, folder, extensions in SECTIONS:
        lines.append(f"\t\tpublic static class {section_name}")
        lines.append("\t\t{")

        for asset in iter_assets(folder, extensions):
            lines.append(
                f'\t\t\tpublic const string {constant_name(asset.stem)} = @"{content_path(asset)}";'
            )

        lines.append("\t\t}")
        lines.append("")

    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
